#ifndef BITCOIN_SCRIPT_STANDARD_H
#include <script/interpreter.h>
#define BITCOIN_SCRIPT_STANDARD_H

enum class TxoutType {
    NONSTANDARD,
    PUBKEY,
    PUBKEYHASH,
    SCRIPTHASH,
    MULTISIG,
    NULL_DATA,
    WITNESS_V0_KEYHASH,
    WITNESS_V0_SCRIPTHASH,
    WITNESS_V1_TAPROOT,
    QBITX_DILITHIUM,
    DILITHIUM_PUBKEY,
    DILITHIUM_PUBKEYHASH,
    DILITHIUM_SCRIPTHASH,
    DILITHIUM_WITNESS_V0_KEYHASH,
    DILITHIUM_WITNESS_V0_SCRIPTHASH,
    DILITHIUM_MULTISIG,
    WITNESS_UNKNOWN,
};

#endif // BITCOIN_SCRIPT_STANDARD_H
